
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ReduxProvider } from "../lib/provider";
import { Sidebar } from "@/components/Sidebar";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ReduxProvider>
            <div className="relative flex min-h-screen bg-white dark:bg-black">

              {/* Sidebar */}
              <aside className="fixed left-0 top-0 z-40 h-screen">
                <Sidebar />
              </aside>

              {/* Main Content */}
              <main
                className="
                  flex-1
                  ml-[80px]
                  transition-all
                  duration-300
                  ease-in-out
                  dark:text-gray-100
                  text-gray-900
                "
              >
                {/* when on /home we expand sidebar */}
                <div className="max-w-[630px] mx-auto px-4 py-6">
                  {children}
                </div>
              </main>

              <Toaster position="top-center" reverseOrder={false} />
            </div>
          </ReduxProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
