
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Heart, Home, MessageCircleMoreIcon, MoreHorizontalIcon, PlusSquareIcon, Search, User } from 'lucide-react'
import { ThemeProvider } from "@/components/theme-provider";
import Image from "next/image";
import Link from "next/link";
import { Provider } from "react-redux";
import { ReduxProvider } from "../lib/provider";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange>
          <div className="flex items-start justify-start gap-[20px]">
            <div className="flex flex-col justify-between h-screen w-64 border-r border-gray-200 bg-white p-4">
              <div className="flex items-center mb-8">
                <Image
                  src="/print-204012271.webp"
                  alt="Instagram Logo"
                  width={120}
                  height={40}
                  className="cursor-pointer hover:opacity-80 transition"
                />
              </div>

              <div className="flex flex-col gap-4 text-gray-800 font-medium">
                <Link href={'/home'} className="flex items-center gap-3 p-2 rounded-lg cursor-pointer hover:bg-gray-100 transition">
                  <Home className="w-6 h-6" />
                  <span>Home</span>
                </Link>
                <Link href={'/search'} className="flex items-center gap-3 p-2 rounded-lg cursor-pointer hover:bg-gray-100 transition">
                  <Search className="w-6 h-6" />
                  <span>Search</span>
                </Link>
                <Link href={'/explore'} className="flex items-center gap-3 p-2 rounded-lg cursor-pointer hover:bg-gray-100 transition">
                  <svg
                    aria-label="Explore"
                    className="w-6 h-6"
                    fill="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <title>Explore</title>
                    <polygon
                      fill="none"
                      points="13.941 13.953 7.581 16.424 10.06 10.056 16.42 7.585 13.941 13.953"
                      stroke="currentColor"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth="2"
                    ></polygon>
                    <polygon
                      fillRule="evenodd"
                      points="10.06 10.056 13.949 13.945 7.581 16.424 10.06 10.056"
                    ></polygon>
                    <circle
                      cx="12.001"
                      cy="12.005"
                      fill="none"
                      r="10.5"
                      stroke="currentColor"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth="2"
                    ></circle>
                  </svg>
                  <span>Explore</span>
                </Link>
                <Link href={'/reels'} className="flex items-center gap-3 p-2 rounded-lg cursor-pointer hover:bg-gray-100 transition">
                  <svg aria-label="Reels" className="x1lliihq x1n2onr6 x5n08af" fill="currentColor" height="24" role="img" viewBox="0 0 24 24" width="24"><title>Reels</title><path d="M22.935 7.468c-.063-1.36-.307-2.142-.512-2.67a5.341 5.341 0 0 0-1.27-1.95 5.345 5.345 0 0 0-1.95-1.27c-.53-.206-1.311-.45-2.672-.513C15.333 1.012 14.976 1 12 1s-3.333.012-4.532.065c-1.36.063-2.142.307-2.67.512-.77.298-1.371.69-1.95 1.27a5.36 5.36 0 0 0-1.27 1.95c-.206.53-.45 1.311-.513 2.672C1.012 8.667 1 9.024 1 12s.012 3.333.065 4.532c.063 1.36.307 2.142.512 2.67.297.77.69 1.372 1.27 1.95.58.581 1.181.974 1.95 1.27.53.206 1.311.45 2.672.513C8.667 22.988 9.024 23 12 23s3.333-.012 4.532-.065c1.36-.063 2.142-.307 2.67-.512a5.33 5.33 0 0 0 1.95-1.27 5.356 5.356 0 0 0 1.27-1.95c.206-.53.45-1.311.513-2.672.053-1.198.065-1.555.065-4.531s-.012-3.333-.065-4.532Zm-1.998 8.972c-.05 1.07-.228 1.652-.38 2.04-.197.51-.434.874-.82 1.258a3.362 3.362 0 0 1-1.258.82c-.387.151-.97.33-2.038.379-1.162.052-1.51.063-4.441.063s-3.28-.01-4.44-.063c-1.07-.05-1.652-.228-2.04-.38a3.354 3.354 0 0 1-1.258-.82 3.362 3.362 0 0 1-.82-1.258c-.151-.387-.33-.97-.379-2.038C3.011 15.28 3 14.931 3 12s.01-3.28.063-4.44c.05-1.07.228-1.652.38-2.04.197-.51.434-.875.82-1.26a3.372 3.372 0 0 1 1.258-.819c.387-.15.97-.329 2.038-.378C8.72 3.011 9.069 3 12 3s3.28.01 4.44.063c1.07.05 1.652.228 2.04.38.51.197.874.433 1.258.82.385.382.622.747.82 1.258.151.387.33.97.379 2.038C20.989 8.72 21 9.069 21 12s-.01 3.28-.063 4.44Zm-4.584-6.828-5.25-3a2.725 2.725 0 0 0-2.745.01A2.722 2.722 0 0 0 6.988 9v6c0 .992.512 1.88 1.37 2.379.432.25.906.376 1.38.376.468 0 .937-.123 1.365-.367l5.25-3c.868-.496 1.385-1.389 1.385-2.388s-.517-1.892-1.385-2.388Zm-.993 3.04-5.25 3a.74.74 0 0 1-.748-.003.74.74 0 0 1-.374-.649V9a.74.74 0 0 1 .374-.65.737.737 0 0 1 .748-.002l5.25 3c.341.196.378.521.378.652s-.037.456-.378.651Z"></path></svg>            <span>Reels</span>
                </Link>
                <Link href={'/messages'} className="flex items-center gap-3 p-2 rounded-lg cursor-pointer hover:bg-gray-100 transition">
                  <MessageCircleMoreIcon className="w-6 h-6" />
                  <span>Messages</span>
                </Link>
                <Link href={'/notifications'} className="flex items-center gap-3 p-2 rounded-lg cursor-pointer hover:bg-gray-100 transition">
                  <Heart className="w-6 h-6" />
                  <span>Notifications</span>
                </Link>
                <Link href={'/create'} className="flex items-center gap-3 p-2 rounded-lg cursor-pointer hover:bg-gray-100 transition">
                  <PlusSquareIcon className="w-6 h-6" />
                  <span>Create</span>
                </Link>
                <Link href={'/profile'} className="flex items-center gap-3 p-2 rounded-lg cursor-pointer hover:bg-gray-100 transition">
                  <User className="w-6 h-6 rounded-full border border-gray-300" />
                  <span>Profile</span>
                </Link>
              </div>

              <div className="flex flex-col gap-4 mt-6">
                <Link href={'/more'} className="flex items-center gap-3 p-2 rounded-lg cursor-pointer hover:bg-gray-100 transition">
                  <span className="text-xl">☰</span>
                  <span>More</span>
                </Link>
                <Link href={'/also'} className="flex items-center gap-3 p-2 rounded-lg cursor-pointer hover:bg-gray-100 transition">
                  <span className="grid grid-cols-2 gap-0.5 w-6 h-6 text-gray-600">
                    <span className="bg-gray-400"></span>
                    <span className="bg-gray-400"></span>
                    <span className="bg-gray-400"></span>
                    <span className="bg-gray-400"></span>
                  </span>
                  <span>Also from Meta</span>
                </Link>
              </div>
            </div>
            <div className="p-[10px]">
              <ReduxProvider>
                {children}
              </ReduxProvider>
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
